language: r
cache: packages
r:
  - release
  - devel
addons:
  apt:
    sourceline:
      - 'deb http://us.archive.ubuntu.com/ubuntu xenial universe'
    packages:
      - python3-rdkit
github_packages:
  - r-lib/covr
  - jranke/webchem@bcpc
after_success:
  - Rscript -e 'covr::codecov()'
