language: c
sudo: required
dist: focal

jobs:
  include:
    - name: linux
      os: linux

env:
  global:
    - USE_BSPM="true"

before_install:
  - curl -OLs https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_all

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

after_success:
  - travis_wait ./run.sh coverage
